//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string BookingID { get; set; }
        public decimal PassengerID { get; set; }
        public string FlightID { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
